import logo1 from '../public/assets/clients2/Property 1=Variant2.svg'
import logo2 from '../public/assets/clients2/Property 1=Variant2 (1).svg'
import logo3 from '../public/assets/clients2/Property 1=Variant2 (2).svg'
import logo4 from '../public/assets/clients2/Property 1=Variant2 (3).svg'
import logo5 from '../public/assets/clients2/Property 1=Variant2 (4).svg'
import logo6 from '../public/assets/clients2/Property 1=Variant2 (5).svg'
import logo7 from '../public/assets/clients2/Property 1=Variant2 (6).svg'
import logo8 from '../public/assets/clients2/Property 1=Variant2 (7).svg'
import logo9 from '../public/assets/clients2/Property 1=Variant2 (8).svg'
import logo10 from '../public/assets/clients2/Property 1=Variant2 (9).svg'
import logo11 from '../public/assets/clients2/Property 1=Variant2 (10).svg'
import logo12 from '../public/assets/clients2/Property 1=Variant2 (11).svg'
import logo13 from '../public/assets/clients2/Property 1=Variant2 (12).svg'
import logo14 from '../public/assets/clients2/Property 1=Variant2 (13).svg'
import logo15 from '../public/assets/clients2/Property 1=Variant2 (14).svg'
import logo16 from '../public/assets/clients2/Property 1=Variant2 (15).svg'
import logo17 from '../public/assets/clients2/Property 1=Variant2 (16).svg'
import logo18 from '../public/assets/clients2/Property 1=Variant2 (17).svg'
import logo19 from '../public/assets/clients2/Property 1=Variant2 (18).svg'
import logo20 from '../public/assets/clients2/Property 1=Variant2 (19).svg'
import logo21 from '../public/assets/clients2/Property 1=Variant2 (20).svg'
import logo22 from '../public/assets/clients2/Property 1=Variant2 (21).svg'
import logo23 from '../public/assets/clients2/Property 1=Variant2 (22).svg'
export const clients=[
    logo3,logo2,logo1,logo4,logo5,logo6,logo7,logo8,logo9,logo10,logo11,logo12,logo13,logo14,logo15,logo16,logo17,logo18,logo19,logo20,logo21,logo22,logo23
]