import logo1 from '../public/assets/clients/Property 1=Variant2-1.png'
import logo2 from '../public/assets/clients/Property 1=Variant2-2.png'
import logo3 from '../public/assets/clients/Property 1=Variant2-3.png'
import logo4 from '../public/assets/clients/Property 1=Variant2-4.png'
import logo5 from '../public/assets/clients/Property 1=Variant2-5.png'
import logo6 from '../public/assets/clients/Property 1=Variant2-6.png'
import logo7 from '../public/assets/clients/Property 1=Variant2-7.png'
import logo8 from '../public/assets/clients/Property 1=Variant2-8.png'
import logo9 from '../public/assets/clients/Property 1=Variant2-9.png'
import logo10 from '../public/assets/clients/Property 1=Variant2-10.png'
import logo11 from '../public/assets/clients/Property 1=Variant2-11.png'
import logo12 from '../public/assets/clients/Property 1=Variant2-12.png'
import logo13 from '../public/assets/clients/Property 1=Variant2-13.png'
import logo14 from '../public/assets/clients/Property 1=Variant2-14.png'
import logo15 from '../public/assets/clients/Property 1=Variant2-15.png'
import logo16 from '../public/assets/clients/Property 1=Variant2-16.png'
import logo17 from '../public/assets/clients/Property 1=Variant2-17.png'
import logo18 from '../public/assets/clients/Property 1=Variant2-18.png'
import logo19 from '../public/assets/clients/Property 1=Variant2-19.png'
import logo20 from '../public/assets/clients/Property 1=Variant2-20.png'
import logo21 from '../public/assets/clients/Property 1=Variant2-21.png'
import logo22 from '../public/assets/clients/Property 1=Variant2-22.png'
import logo23 from '../public/assets/clients/Property 1=Variant2.png'
export const clients=[
    logo23,logo2,logo3,logo4,logo5,logo6,logo7,logo8,logo9,logo10,logo11,logo12,logo13,logo14,logo15,logo16,logo17,logo18,logo19,logo20,logo21,logo22,logo1
]